### ISSUE TITLE
Exception 'NoneType' object has no attribute 'detail'

### ISSUE THREAD

**Issue by vsel** [mail-in-a-box/free_tls_certificates#10]
In case when there is no error property in ChallengeBody we have a 
`message = '; '.join(c.error.detail for c in challg.challenges if c.status.name == "invalid")
AttributeError: 'NoneType' object has no attribute 'detail'`
So we need read uri instead. 
And then we will have error like this
`The HTTP Validation challenge for daridana.ru failed: https://acme-v01.api.letsencrypt.org/acme/challenge/blablabla; "*****.com" was considered an unsafe domain by a third-party API.`

**Comment by vsel** [comment]
[My fix](https://github.com/mail-in-a-box/free_tls_certificates/pull/11)

**Comment by JoshData** [comment]
This repo is now unmaintained since I'm no longer using it as a part of http://github.com/mail-in-a-box/mailinabox. Thanks.
