### ISSUE TITLE
acme.challenges.HTTP01 has no attribude CONTENT_TYPE

### ISSUE THREAD

**Issue by azurit** [mail-in-a-box/free_tls_certificates#6]
Function answer_challenge_http is trying to return CONTENT_TYPE attribute of acme.challenges.HTTP01 object - there's no such attribude (maybe it was removed from acme library?).

**Comment by JoshData** [comment]
Seems so:

https://github.com/letsencrypt/letsencrypt/commit/c175ff955efcf3659d294827c6d49a55200a20b8

Thanks!
