### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by azurit** [mail-in-a-box/free_tls_certificates#7]
Adding Python 2.7 support is extremely easy, why not doing it? As far as i tested it, only two things are needed:
- change 'print' syntax based on Python version
- domain names for issue_certificate function in Python 2.7 must be provided in unicode ([u'domain1', u'domain2', ...]) so only example code must be changed

**Comment by JoshData** [comment]
For the second point, let's just have the library accept Py2 `str`s too. We should in any case _not_ accept Unicode characters because domains should be IDNA-encoded anyway (or if we do, we have to IDNA-encode it).

**Comment by azurit** [comment]
you can also accept unicode characters and encode it to punnycode, it's extremely easy, here is the code which i'm using:

``` python
from encodings import idna

def _domain_to_punycode(domain):
    if not domain:
        return ""
    if not isinstance(domain, unicode):
        domain = domain.decode("UTF-8")
    domain = domain.split(".")
    for i in xrange(len(domain)):
        domain[i] = idna.ToASCII(domain[i])
    return ".".join(domain)
```

**Comment by JoshData** [comment]
Python's built-in idna encoding is actually outdated - the spec has changed. There's an `idna` module that I've used elsewhere which has been really great.
